[project]
name = "notebooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cartopy>=0.24.1",
    "duckdb>=1.5.2",
    "dynamical-catalog>=0.5.0",
    "gribberish>=1.5.0",
    "matplotlib>=3.10.1",
    "metpy>=1.7.1",
    "pandas>=2.2.3",
    "rioxarray>=0.19.0",
    "zarr>=3.2.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "nbclient>=0.10.4",
    "nbformat>=5.10.4",
]
